% Script for testing and messing around with the Inverse Gaussian function
% close all
% clear all
% Setting up a h array
h = [0:0.0001:0.1]';
% Running the function, the second and third inputs to the function set the
% mew and lamda values respectively
results = DWFFloor(h, 0.033, 0.07, 0.1*(500/9)^2)';
% Plotting
figure
tiledlayout(1, 2)
nexttile
plot(h, results)
xlabel('Rear ride height (m)')
ylabel('Downforce generated by floor (N)')
title('Downforce as a function of ride height')

%% Checking against downforce generated from upper aero elements
vCar = [0:0.1:320]';
DWFUpper = 0.365 * (vCar * 1000/(60 * 60)).^2 ;
% Plotting
nexttile
plot(vCar, DWFUpper)
xlabel('vCar (kph)')
ylabel('Downforce generated by the upper aero elements (N)')
title('Downforce as a function of vCar')

%% Getting DWF values at 200kph and corresponding ride height
query1 = interp1(h, results, 0.06);
disp(query1)
query2 = interp1(vCar, DWFUpper, 200);
disp(query2)