% Script for testing and messing around with the Inverse Gaussian function
% Setting up a h array
h = [0:0.1:100]';
% Running the function, the second and third inputs to the function set the
% mew and lamda values respectively
results = DWFFloor(h, 35, 8, 2.3*(500/9)^2)';
% Plotting
figure
plot(h, results)
xlabel('Rear ride height (mm)')
ylabel('Downforce generated by floor (N)')
title('Downforce as a function of ride height')

%% Checking against downforce generated from upper aero elements
vCar = [0:0.1:320]';
DWFUpper = 0.365 * (vCar * 1000/(60 * 60)).^2 ;
% Plotting
figure
plot(vCar, DWFUpper)
xlabel('vCar (kph)')
ylabel('Downforce generated by the upper aero elements (N)')
title('Downforce as a function of vCar')