%% Defining the function for the Inverse Gaussian distribution which will be used to calculate the downforce generated by the 
% floor of the car in the quarter car model
function LND = DWFFloorNew(h, mew, std, scaling)
% Determining the InvGauss values
LND = lognpdf(h, mew, std);
% Scaling the output
LND = LND.*scaling;
% Replacing any NaN values with 0, in early testing these have only popped
% up when ride height is 0 so for the moment this is fine to do (23/11/2023)
LND(isnan(LND), 1) = 0;
% Replacing any value of downforce which was generated with a negative ride
% heigh with 0, for the moment this is a quick fix to stop negative ride
% height values bombing the model.
LND(h<0) = 0;